DROP ROLE IF EXISTS 'admin';
CREATE ROLE 'admin';
GRANT ALL PRIVILEGES ON la_tocanita.* TO 'admin' WITH GRANT OPTION;
DROP ROLE IF EXISTS 'Gerente';
CREATE ROLE 'Gerente';
GRANT SELECT ON la_tocanita.* TO 'Gerente' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON la_tocanita.cargo TO 'Gerente' WITH GRANT OPTION;
DROP ROLE IF EXISTS 'Contador';
CREATE ROLE 'Contador';
GRANT SELECT ON la_tocanita.compra TO 'Contador';
GRANT SELECT ON la_tocanita.compra_insumos TO 'Contador';
GRANT SELECT ON la_tocanita.nomina TO 'Contador';
GRANT SELECT ON la_tocanita.venta TO 'Contador';
GRANT SELECT ON la_tocanita.venta_productos TO 'Contador';
GRANT SELECT ON la_tocanita.vw_info_compra_insumos TO 'Contador';
GRANT SELECT ON la_tocanita.vw_info_nomina TO 'Contador';
GRANT SELECT ON la_tocanita.vw_info_venta TO 'Contador';
DROP ROLE IF EXISTS 'adminRecHumanos';
CREATE ROLE 'adminRecHumanos';
GRANT SELECT ON la_tocanita.cargo TO 'adminRecHumanos';
GRANT ALL PRIVILEGES ON la_tocanita.trabajador TO 'adminRecHumanos';
GRANT SELECT ON la_tocanita.vw_info_cargo_trabajador TO 'adminRecHumanos';
DROP ROLE IF EXISTS 'Jefe de Ventas';
CREATE ROLE 'Jefe de Ventas';
GRANT SELECT ON la_tocanita.cargamento TO 'Jefe de Ventas';
GRANT ALL PRIVILEGES ON la_tocanita.cliente TO 'Jefe de Ventas';
GRANT ALL PRIVILEGES ON la_tocanita.geografia TO 'Jefe de Ventas';
GRANT ALL PRIVILEGES ON la_tocanita.proveedor TO 'Jefe de Ventas';
GRANT ALL PRIVILEGES ON la_tocanita.venta TO 'Jefe de Ventas';
GRANT ALL PRIVILEGES ON la_tocanita.venta_productos TO 'Jefe de Ventas';
GRANT SELECT ON la_tocanita.vw_info_venta TO 'Jefe de Ventas';
GRANT SELECT ON la_tocanita.vw_info_cliente_numeroCompras TO 'Jefe de Ventas';
DROP ROLE IF EXISTS 'Auxiliar Contable';
CREATE ROLE 'Auxiliar Contable';
GRANT ALL PRIVILEGES ON la_tocanita.compra TO 'Auxiliar Contable';
GRANT ALL PRIVILEGES ON la_tocanita.compra_insumos TO 'Auxiliar Contable';
GRANT ALL PRIVILEGES ON la_tocanita.venta TO 'Auxiliar Contable';
GRANT ALL PRIVILEGES ON la_tocanita.venta_productos TO 'Auxiliar Contable';
GRANT SELECT ON la_tocanita.vw_info_compra_insumos TO 'Auxiliar Contable';
GRANT SELECT ON la_tocanita.vw_info_nomina TO 'Auxiliar Contable';
GRANT SELECT ON la_tocanita.vw_info_venta TO 'Auxiliar Contable';
DROP ROLE IF EXISTS 'Jefe de Produccion';
CREATE ROLE 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.insumo TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.produccion TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.produccion_insumos_daily TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.produccion_trabajador_daily TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.producto TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.resultado_produccion_daily TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.vw_info_produccion TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.vw_info_produccion_trabajador TO 'Jefe de Produccion';
GRANT SELECT ON la_tocanita.vw_info_produccion_promedio TO 'Jefe de Produccion';
DROP ROLE IF EXISTS 'Linea de Produccion';
CREATE ROLE 'Linea de Produccion';
GRANT ALL PRIVILEGES ON la_tocanita.insumo TO 'Linea de Produccion';
GRANT ALL PRIVILEGES ON la_tocanita.produccion TO 'Linea de Produccion';
GRANT ALL PRIVILEGES ON la_tocanita.produccion_insumos_daily TO 'Linea de Produccion';
GRANT ALL PRIVILEGES ON la_tocanita.produccion_trabajador_daily TO 'Linea de Produccion';
GRANT ALL PRIVILEGES ON la_tocanita.producto TO 'Linea de Produccion';
GRANT ALL PRIVILEGES ON la_tocanita.resultado_produccion_daily TO 'Linea de Produccion';
GRANT SELECT ON la_tocanita.vw_info_produccion TO 'Linea de Produccion';
GRANT SELECT ON la_tocanita.vw_info_produccion_trabajador TO 'Linea de Produccion';
DROP ROLE IF EXISTS 'Conductor';
CREATE ROLE 'Conductor';
GRANT ALL PRIVILEGES ON la_tocanita.cargamento TO 'Conductor';
GRANT SELECT ON la_tocanita.geografia TO 'Conductor';

-- Para ver el acceso a las tablas en el back-end
GRANT SELECT ON mysql.* TO 'admin','Gerente','Contador','adminRecHumanos','Jefe de Ventas',
'Auxiliar Contable', 'Jefe de Produccion', 'Linea de Produccion', 'Conductor';

SHOW GRANTS FOR 'Gerente'@'%';